/**
 * Since airbnb is deprecated and incompatible with ESLint 9+, we'll use our own rules.
 * Omits formatting/layout rules removed from ESLint core (Prettier covers those).
 */
module.exports = {
  plugins: ["import", "@typescript-eslint"],
  rules: {
    // Best practices
    "array-callback-return": ["error", { allowImplicit: true }],
    "block-scoped-var": "error",
    "consistent-return": "error",
    "default-case": ["error", { commentPattern: "^no default$" }],
    "default-case-last": "error",
    "default-param-last": "off",
    "@typescript-eslint/default-param-last": "error",
    "dot-notation": "off",
    "@typescript-eslint/dot-notation": ["error", { allowKeywords: true }],
    eqeqeq: ["error", "always", { null: "ignore" }],
    "grouped-accessor-pairs": "error",
    "guard-for-in": "error",
    "no-alert": "warn",
    "no-caller": "error",
    "no-constructor-return": "error",
    "no-else-return": ["error", { allowElseIf: false }],
    "no-empty-function": "off",
    "@typescript-eslint/no-empty-function": [
      "error",
      {
        allow: ["arrowFunctions", "functions", "methods"],
      },
    ],
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-implied-eval": "off",
    "no-new-func": "off",
    "@typescript-eslint/no-implied-eval": "error",
    "no-iterator": "error",
    "no-labels": ["error", { allowLoop: false, allowSwitch: false }],
    "no-lone-blocks": "error",
    "no-loop-func": "off",
    "@typescript-eslint/no-loop-func": "error",
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-wrappers": "error",
    "no-octal-escape": "error",
    "no-param-reassign": [
      "error",
      {
        props: true,
        ignorePropertyModificationsFor: [
          "acc",
          "accumulator",
          "e",
          "ctx",
          "context",
          "req",
          "request",
          "res",
          "response",
          "$scope",
          "staticContext",
        ],
      },
    ],
    "no-proto": "error",
    "no-return-assign": ["error", "always"],
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "off",
    "@typescript-eslint/only-throw-error": "error",
    "no-unmodified-loop-condition": "off",
    "no-unused-expressions": "off",
    "@typescript-eslint/no-unused-expressions": [
      "error",
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
      },
    ],
    "no-useless-concat": "error",
    "no-useless-return": "error",
    "no-void": "error",
    "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
    radix: "error",
    "vars-on-top": "error",
    yoda: "error",

    // Variables
    "no-label-var": "error",
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": "error",
    "no-undef-init": "error",

    // ES6
    "no-duplicate-imports": "off",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "off",
    "@typescript-eslint/no-useless-constructor": "error",
    "no-var": "error",
    "prefer-const": [
      "error",
      {
        destructuring: "any",
        ignoreReadBeforeAssign: true,
      },
    ],
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "symbol-description": "error",

    // Imports (non-stylistic)
    "import/export": "error",
    "import/no-mutable-exports": "error",
    "import/no-amd": "error",
    "import/first": "error",
    "import/no-duplicates": "error",
    "import/no-named-default": "error",
    "import/no-absolute-path": "error",
    "import/no-dynamic-require": "error",
    "import/no-webpack-loader-syntax": "error",
    "import/no-self-import": "error",
    "import/no-useless-path-segments": ["error", { commonjs: true }],
  },
};
